create table if not exists factory_support_launcher_mapping_level(
set_id Integer not null,
factory_support_id Integer null,
mapping_effective_date varchar(255) null,
mapping_code Integer null,
mapping_decsription varchar(255) null,
hierarchy_lvl1 varchar(255) null,
hierarchy_lvl1_desc varchar(255) null,
hierarchy_lvl2 varchar(255) null,
hierarchy_lvl2_desc varchar(255) null,
hierarchy_lvl3 varchar(255) null,
hierarchy_lvl3_desc varchar(255) null,
hierarchy_lvl4 varchar(255) null,
hierarchy_lvl4_desc varchar(255) null,
hierarchy_lvl5 varchar(255) null,
hierarchy_lvl5_desc varchar(255) null,
hierarchy_lvl6 varchar(255) null,
hierarchy_lvl6_desc varchar(255) null,
hierarchy_lvl7 varchar(255) null,
hierarchy_lvl7_desc varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint factory_support_launcher_mapping_level_pk primary key(set_id));